version: '3.8'

services:
  db:
    image: postgres:16
    container_name: planner-db
    environment:
      POSTGRES_DB: planner
      POSTGRES_USER: planner_user
      POSTGRES_PASSWORD: planner_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./planeador
      dockerfile: Dockerfile
    image: planner-backend
    container_name: planner-backend
    depends_on:
      - db
    environment:
      # Conecta Spring Boot con Postgres dentro de la red de Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/planner
      SPRING_DATASOURCE_USERNAME: planner_user
      SPRING_DATASOURCE_PASSWORD: planner_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    image: planner-frontend
    container_name: planner-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
